export const constellationNames = [
    'Andromedae',
    'Antillae',
    'Apodis',
    'Aquarii',
    'Aquilae',
    'Arae',
    'Arietis',
    'Aurigae',
    'Bootis',
    'Caeli',
    'Camelopardalis',
    'Cancri',
    'Canum Venaticorum',
    'Canis Majoris',
    'Canis Minoris',
    'Capricorni',
    'Carinae',
    'Cassiopeiae',
    'Centauri',
    'Cephei',
    'Chamaeleontis',
    'Circini',
    'Columbae',
    'Comae Berenices',
    'Coronae Australis',
    'Coronae Borealis',
    'Corvi',
    'Crateris',
    'Crucis',
    'Cygni',
    'Delphini',
    'Doradus',
    'Draconis',
    'Equulei',
    'Eridani',
    'Fornacis',
    'Geminorum',
    'Gruis',
    'Herculis',
    'Horologii',
    'Hydrae',
    'Hydri',
    'Indi',
    'Lacertae',
    'Leonis',
    'Leonis Majoris',
    'Leporis',
    'Librae',
    'Lupi',
    'Lyncis',
    'Lyrae',
    'Mensae',
    'Microscopii',
    'Monocerotis',
    'Muscae',
    'Normae',
    'Octanis',
    'Ophiuchi',
    'Orionis',
    'Pavonis',
    'Pegasi',
    'Persei',
    'Phoenicis',
    'Pictoris',
    'Piscium',
    'Piscis Austrini',
    'Puppis',
    'Pyxidis',
    'Reticuli',
    'Sagittae',
    'Sagittarii',
    'Scorpii',
    'Sculptoris',
    'Scuti',
    'Serpentis',
    'Sextantis',
    'Tauri',
    'Telescopii',
    'Trianguli',
    'Trianguli Australis',
    'Tucanae',
    'Ursae Majoris',
    'Ursae Minoris',
    'Velorum',
    'Virginis',
    'Volantis',
    'Vulpeulae'
];